# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env: 
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd src
      - yarn

  build:
    commands:
      - echo Build started on `date`
      - yarn build
      - yarn test
      - echo Build completed on `date`
  post_build:
    commands:
      - yarn sls deploy --verbose --stage $STAGE --force
# Include only the files required for your application to run.
# artifacts:
#   files:
#     - catalog-ui/dist/**/*
