const mockData = [
  {
    APP: 73385,
    FY: 2019,
    ad1: '528 Hennepin Ave',
    ad2: 'Ste 400',
    city: 'Mankato',
    description:
      "The mission of Zenon Dance Company and School, Inc. is to sustain an artistically excellent, professional dance company in the Twin Cities by presenting the commissioned works of emerging and locally, nationally, and internationally recognized modern and jazz choreographers to the broadest and most diverse audiences and communities possible, including those with disabilities. Zenon accomplishes this through performance, education, and outreach. Zenon's school provides high quality dance instruction for avocational to professional dancers in a diverse curriculum.",
    discipline: 'Dance, modern',
    discipline2: 'Dance, ethnic/jazz/folk-ins',
    email: 'marasmail@yahoo.com',
    email_2nd: '',
    legalname: 'Zenon Dance Company and School, Inc.',
    lnam: 'Zenon Dance Company and School, Inc.',
    name: 'Zenon Dance Company and School, Inc.',
    phone: '(612) 338-1101',
    primary_contact: 'Mara Winke, Managing Director',
    st: 'MN',
    type: 'Performing Group',
    type2: 'School of the Arts',
    url: 'https://www.zenondance.org/',
    zip: '55403-1810',
  },
  {
    APP: 73368,
    FY: 2019,
    ad1: '3012 Minnehaha Ave S',
    ad2: '',
    city: 'Minneapolis',
    description:
      'The mission of Zorongo Flamenco Dance Theatre and School is to enrich our community by drawing people close to the beauty and energy of the flamenco tradition and, by expanding on that tradition, create an innovative art form that explores the issues of contemporary life.',
    discipline: 'Dance, ethnic/jazz/folk-ins',
    discipline2: 'Music, ethnic/folk-inspired',
    email: 'zorongoflamenco@gmail.com',
    email_2nd: '',
    legalname: 'Zorongo Flamenco, Inc.',
    lnam: 'Zorongo Flamenco, Inc.',
    name: 'Zorongo Flamenco Dance Theatre and School',
    phone: '(612) 234-1653',
    primary_contact: 'G. Michael Bargas, Managing Director',
    st: 'MN',
    type: 'Performing Group',
    type2: 'School of the Arts',
    url: 'http://www.zorongo.org/',
    zip: '55406-1932',
  },
];

module.exports = mockData;
