const mockData = [
  {
    name: 'Zenon Dance Company and School, Inc.',
    discipline: 'Dance, modern',
    discipline2: 'Dance, ethnic/jazz/folk-ins',
    type: 'Performing Group',
    type2: 'School of the Arts',
    url: 'https://www.zenondance.org/',
    phone: '(612) 338-1101',
    email: 'marasmail@yahoo.com',
    email_2nd: '',
    ad1: '528 Hennepin Ave',
    ad2: 'Ste 400',
    city: 'Mankato',
    st: 'MN',
    zip: '55403-1810',
    primary_contact: 'Mara Winke, Managing Director',
    description:
      "The mission of Zenon Dance Company and School, Inc. is to sustain an artistically excellent, professional dance company in the Twin Cities by presenting the commissioned works of emerging and locally, nationally, and internationally recognized modern and jazz choreographers to the broadest and most diverse audiences and communities possible, including those with disabilities. Zenon accomplishes this through performance, education, and outreach. Zenon's school provides high quality dance instruction for avocational to professional dancers in a diverse curriculum.",
    APP: 73385,
    FY: 2019,
    lnam: 'Zenon Dance Company and School, Inc.',
    legalname: 'Zenon Dance Company and School, Inc.',
  },
  {
    name: 'Zorongo Flamenco Dance Theatre and School',
    discipline: 'Dance, ethnic/jazz/folk-ins',
    discipline2: 'Music, ethnic/folk-inspired',
    type: 'Performing Group',
    type2: 'School of the Arts',
    url: 'http://www.zorongo.org/',
    phone: '(612) 234-1653',
    email: 'zorongoflamenco@gmail.com',
    email_2nd: '',
    ad1: '3012 Minnehaha Ave S',
    ad2: '',
    city: 'Minneapolis',
    st: 'MN',
    zip: '55406-1932',
    primary_contact: 'G. Michael Bargas, Managing Director',
    description:
      'The mission of Zorongo Flamenco Dance Theatre and School is to enrich our community by drawing people close to the beauty and energy of the flamenco tradition and, by expanding on that tradition, create an innovative art form that explores the issues of contemporary life.',
    APP: 73368,
    FY: 2019,
    lnam: 'Zorongo Flamenco, Inc.',
    legalname: 'Zorongo Flamenco, Inc.',
  },
];

module.exports = mockData;
