certificateId: .
domainNameRoot: .
emailGateway: dummy
emailUsername: .
emailPassword: .
googleGeocodingApiKey: ${env:GOOGLE_GEOCODING_API_KEY}
googleCaptchaKey: .
googleCaptchaGateway: noop
lambdaExecutionRole: .
