export const defaultForm = {
  update: {
    entityId: '',
    actionType: '',
  },
  formDirty: false,
  gresp: '',
  name: null,
  category: {
    craft: false,
    dance: false,
    folk: false,
    literary: false,
    music: false,
    photo: false,
    opera: false,
    visual: false,
  },
  website: null,
  street: null,
  city: null,
  state: 'MN',
  zip: null,
  contactName: null,
  contactEmail: null,
  contactPhone: null,
  description: null,
  image: null,
  approved: false,
  base64Image: null,
};
