name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build MSAB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint
