name: MSAB Pull Requests
on:
  pull_request:
jobs:
  build:
    name: Build MSAB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - run: npm i
    - run: npm run build
    - run: npm run test
