name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set archive name
      run: echo "ARCHIVE=msab-arts-locator_${{ env.TAG }}.zip" >> $GITHUB_ENV
    - run: echo "module.exports = { version: '${{ env.TAG }}' };" > release_info.js
    - name: bundle release artifact
      run: zip ${{ env.ARCHIVE }} -r .
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        artifacts: ${{ env.ARCHIVE }}
        token: ${{ secrets.GITHUB_TOKEN }}
